services:
  django:
    build:
      context: ./site
    entrypoint: ./entrypoint.sh
    volumes:
      - ./site:/app
    expose:
      - "8000"
    container_name: B2Reads-django
    depends_on:
      - postgres
      - redis
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgres
      - DB_PORT=5432
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./site/static:/usr/share/nginx/html/static
      - ./site/media:/usr/share/nginx/html/media
    depends_on:
      - django
    container_name: B2Reads-nginx

  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis_data:/data
    container_name: B2Reads-redis

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: B2Reads-postgres


volumes:
  postgres_data:
  redis_data:
